### ISSUE TITLE
Example in README needs updating 

### ISSUE THREAD

**Issue by AliSoftware** [hartbit/Yaap#2]
‪Nice idea and API, nice user case for property wrappers 👍👌

I just saw that the example in the README is not up to date, still uses `minimum.value` and `maximum.value` instead of using directly `minimum` and `maximum`‬ now that they are properties annotated by a property wrapper.

The example in `YaapExample/main.swift` in the repo doesn’t have that issue and seem up to date so it’s just a matter of copy/pasting that back in the README (I’d have done it myself via a PR but I’m writing from my phone so not so convenient to open PRs 😅)

**Comment by hartbit** [comment]
Thanks for pointing this out! I don't know what happened, but all the examples in the README dated from an old version of the project and they all had issues. All is resolved now.
